# Generated by Django 2.2.7 on 2019-11-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minxful_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='pub_date',
        ),
    ]
