# Generated by Django 2.2.7 on 2019-12-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minxful_app', '0005_reply_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(),
        ),
    ]
