# Generated by Django 3.0 on 2019-12-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minxful_app', '0006_auto_20191207_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_name',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
