# Generated by Django 2.2.7 on 2019-12-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minxful_app', '0006_auto_20191207_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
