# Generated by Django 3.0 on 2019-12-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minxful_app', '0007_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
