# Generated by Django 2.2.7 on 2019-12-12 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minxful_app', '0008_remove_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_text',
            field=models.TextField(default=None),
        ),
    ]
