# Generated by Django 2.2.7 on 2019-12-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minxful_app', '0009_auto_20191212_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
